dist: trusty
sudo: required
language: python
services:
- docker
matrix:
  include:
  - name: Virtual Display HUB
    stage: VDI
    language: python
    python:
    - '3.6'
    cache: pip
    addons:
      apt:
        packages:
        - python3-pip
    script:
    - |-
      cd /home/travis/build/bcgov/sae-virtual-display/hub
      bash docker_quayio_push vdi-hub
env:
  global:
  - secure: "0shDUUQjlUiHfzGviWZEKgngwhCqFC1EDnBXVUm/oWMcmqBRcWo3VF+GvfxSXrts8FlUvas5ZUCZlQTRn3NVfnEdhkjUexU8XhOv5wSVk8CV57duPLBtIrJ9xi69mr8o4IN+LKn4JsnewyBYZ36BQEUkQyD/E+90hzeVehy9mPVn98rcZC2zQe5JFYUpu8pgv5PgCnSFx+uAPtgozkhbI8IRdQpzitBH3sZT9pjMbf2MdSjRKep20K9dF+xsu1uWN9tIOx7tvv9IyhxBGzkElcfsa3vNiqf90KHLlY+ic00vCg+e2+n6Gk4tlhJ92ao8LiJ4DMn9H/F3V4q0SfmbhNE4LS1R1GS0fJe2gxs2dGxlfqxq600VrDIlLtL+vFM0a5l6szRSejSLn9kuyuh9bbM1VR160LqZzJuWnB4dky2ZfUn4g8x+mrEGiRQfcQ92oP8B0NjtdasR/ki7it6pwLiHweZ3YENvPqs3ZPSUqSSVWMri2lSoaVpv6hikkV39GlfDwl8GVJ2pU9FYBj7wA1XDNmLqJyYF1R5IQ8Az4Mg66h1gw579sRRDmkJyftbqC37Fe2cXu7C3eGid3Nj2nonHgd8QEOdwiivXhKuxLH7vuOeBxw/EfhDm2XjdYZN8G46O9nIhZ1TLgPgxsLWrfwR/oU54Lg6QUR2MOVmE2mM="
  - secure: "YkvtSn/Trv6suft3NUbwuY+2FzMqI1UXvxCIwtwgQPXA3KWViW/2aXS/8+WzW62FEAPjubZwOpx0W28fI65quIhab5TKq7vP+2X+gkcewa3mrz9PHxSmCmVN19wGsn1IZhrTwBWxLCrsSz30ABwgjVEuEHrPaqbHQCRlqEIf8ECgcOl5gyYP0SUW6j5OaHxySmuR0yaeUeTvijY4a8Ant4GMz3tZ2BLkWjmhIWQt2e5Ga/LDpP6xhbkWSX36/VHzTICPKJuImGM6rW0KLonj98BUmdviX4QN9i/1c79qjkht3UIdgU6AEchIu4BrdN2JDdAeEY5p1qO/QNW4XJdnz+/DD5rhzyBUghXGsvVT7KvzJDP3ziiDrPYvptacmQe6gqroft76py4TMl7Lg2T6knqNm/yNcmFXFXFZwWP+AULSbZDu3Ulxt4EKJvoWC9FVv0hfmArxXswjl2IMeNEsgzcG71qxf7Iz8gZOH/s97S+Gk3O8Wt2nNlkvw9yVlMWw50mngGKB3HWjCFggKIjomeXgs6Dl5pqiKjkqvn458I9CgWu6GpVj45Jjjmk8kDEAc5wfacMAjbRhXH5xvx5GJe/choLF7xDbFa7cVjZ+FMXqTBc9XGoNSxyI/83G9ez78o2Lkdm4rmp0L1aEZ+bGahfCYyYIAAxGTDDybfy1R0E="
  