dist: trusty
sudo: required
language: python
services:
- docker
matrix:
  include:
  - name: Virtual Display HUB
    stage: VDI
    language: python
    python:
    - '3.6'
    cache: pip
    addons:
      apt:
        packages:
        - python3-pip
    script:
    - |-
      cd /home/travis/build/bcgov/sae-virtual-display/hub
      bash docker_quayio_push vdi-hub
env:
  global:
  - secure: "0shDUUQjlUiHfzGviWZEKgngwhCqFC1EDnBXVUm/oWMcmqBRcWo3VF+GvfxSXrts8FlUvas5ZUCZlQTRn3NVfnEdhkjUexU8XhOv5wSVk8CV57duPLBtIrJ9xi69mr8o4IN+LKn4JsnewyBYZ36BQEUkQyD/E+90hzeVehy9mPVn98rcZC2zQe5JFYUpu8pgv5PgCnSFx+uAPtgozkhbI8IRdQpzitBH3sZT9pjMbf2MdSjRKep20K9dF+xsu1uWN9tIOx7tvv9IyhxBGzkElcfsa3vNiqf90KHLlY+ic00vCg+e2+n6Gk4tlhJ92ao8LiJ4DMn9H/F3V4q0SfmbhNE4LS1R1GS0fJe2gxs2dGxlfqxq600VrDIlLtL+vFM0a5l6szRSejSLn9kuyuh9bbM1VR160LqZzJuWnB4dky2ZfUn4g8x+mrEGiRQfcQ92oP8B0NjtdasR/ki7it6pwLiHweZ3YENvPqs3ZPSUqSSVWMri2lSoaVpv6hikkV39GlfDwl8GVJ2pU9FYBj7wA1XDNmLqJyYF1R5IQ8Az4Mg66h1gw579sRRDmkJyftbqC37Fe2cXu7C3eGid3Nj2nonHgd8QEOdwiivXhKuxLH7vuOeBxw/EfhDm2XjdYZN8G46O9nIhZ1TLgPgxsLWrfwR/oU54Lg6QUR2MOVmE2mM="
  - secure: "K1xUSS0KIRK82a/SUTam5pp2s7tL1/4ANsMZhFPAg+1mRtTtRe50dW6ivUlCgEqOSMZm13ztYo8A9M9h0MMM3uDl4aUn3j+RG+VuEN3e2461RII8tf2l1DeyPGhfNCik5fxqUZrw63l/IoGPMy/KHjdLQEMyItj9Ty0bnfZcyI+KGL9GXgjMnKgnzNdeM6j3+xZamPF+3PTkR8HX6ONzp9iXoEhSdVegCBNgc286SCPgojAl3xto2+YLr701qSQrJObqBff3LxOpHEbLcXNdslrFaUdBKc1fmXEZpowcVxqm7k/Cc7jyAmnq/0uc4V8qmg1td9NeymZMfO0PXiJ9DgHgw0UT+tJ2OMbxZgJd0D9zBfpzQnzV4IZa3iweumwZjgD9jOiy1mijDfElYixdAZQ+gDktuk9PoBQwiTrAJskA4t8JzBHtqSqwl7yG9dijWkESYLuoYVu9y2vj4ixSqfTWJLHfqL6htauA8PoclPt0qHJ/SCURsO15josP7YfdLSnGEGibNvoGA4BIwubNCEE26uRgTU/j30cLU5kCT6Lq85prxiULlJmYhkAHWmZIf9yTG8Mzl1Q2oUhR5DeI95NaxPEbRTYJaSUI4/TXX9PGahhAqnQauakfqgVtR7ZT9d3jONxDIigZIA1mxnKjHUCUEszLhMjPzeAWMre/mqA="
