dist: trusty
sudo: required
language: python
services:
- docker
matrix:
  include:
  - name: Hub
    stage: Virtual Display Components
    language: python
    script:
    - |-
      cd /home/travis/build/bcgov/sae-virtual-display/hub
      bash ../.travis/docker_quayio_push vdi-hub
  - name: Gatekeeper
    stage: Virtual Display Components
    language: python
    script:
    - |-
      cd /home/travis/build/bcgov/sae-virtual-display/gatekeeper
      bash ../.travis/docker_quayio_push vdi-gatekeeper
  - name: Identity Watcher
    stage: Virtual Display Components
    language: python
    script:
    - |-
      cd /home/travis/build/bcgov/sae-virtual-display/identity-watcher
      bash ../.travis/docker_quayio_push vdi-identity-watcher 
  - name: Init User Identity
    stage: Virtual Display Components
    language: python
    script:
    - |-
      cd /home/travis/build/bcgov/sae-virtual-display/init-user-identity
      bash ../.travis/docker_quayio_push vdi-init-identity
  - name: Session // RStudio
    stage: Virtual Display Components
    language: python
    script:
    - |-
      cd /home/travis/build/bcgov/sae-virtual-display/singleuser-rstudio
      bash ../.travis/docker_quayio_push vdi-session-rstudio
  - name: Session // Browser
    stage: Virtual Display Components
    language: python
    script:
    - |-
      cd /home/travis/build/bcgov/sae-virtual-display/singleuser-browser
      bash ../.travis/docker_quayio_push vdi-session-browser
  - name: Session // Notebook
    stage: Virtual Display Components
    language: python
    script:
    - |-
      cd /home/travis/build/bcgov/sae-virtual-display/singleuser-notebook
      bash ../.travis/docker_quayio_push vdi-session-notebook
  - name: Session // Conda Navigator
    stage: Virtual Display Components
    language: python
    script:
    - |-
      cd /home/travis/build/bcgov/sae-virtual-display/singleuser-navigator
      bash ../.travis/docker_quayio_push vdi-session-navigator
  - name: Session // Data Curator
    stage: Virtual Display Components
    language: python
    script:
    - |-
      cd /home/travis/build/bcgov/sae-virtual-display/singleuser-datacurator
      bash ../.travis/docker_quayio_push vdi-session-datacurator

env:
  global:
  - secure: "0shDUUQjlUiHfzGviWZEKgngwhCqFC1EDnBXVUm/oWMcmqBRcWo3VF+GvfxSXrts8FlUvas5ZUCZlQTRn3NVfnEdhkjUexU8XhOv5wSVk8CV57duPLBtIrJ9xi69mr8o4IN+LKn4JsnewyBYZ36BQEUkQyD/E+90hzeVehy9mPVn98rcZC2zQe5JFYUpu8pgv5PgCnSFx+uAPtgozkhbI8IRdQpzitBH3sZT9pjMbf2MdSjRKep20K9dF+xsu1uWN9tIOx7tvv9IyhxBGzkElcfsa3vNiqf90KHLlY+ic00vCg+e2+n6Gk4tlhJ92ao8LiJ4DMn9H/F3V4q0SfmbhNE4LS1R1GS0fJe2gxs2dGxlfqxq600VrDIlLtL+vFM0a5l6szRSejSLn9kuyuh9bbM1VR160LqZzJuWnB4dky2ZfUn4g8x+mrEGiRQfcQ92oP8B0NjtdasR/ki7it6pwLiHweZ3YENvPqs3ZPSUqSSVWMri2lSoaVpv6hikkV39GlfDwl8GVJ2pU9FYBj7wA1XDNmLqJyYF1R5IQ8Az4Mg66h1gw579sRRDmkJyftbqC37Fe2cXu7C3eGid3Nj2nonHgd8QEOdwiivXhKuxLH7vuOeBxw/EfhDm2XjdYZN8G46O9nIhZ1TLgPgxsLWrfwR/oU54Lg6QUR2MOVmE2mM="
  - secure: "pQKxQGlxlGtSwD0G3i5FBx8HwETSrOW3ZvItEXW4DsyFsfj4nNlC117xwC5GkJeOJrdLoQqKMwkVw1XTAQq/zbC3rJU+BqJ3hGRrKKGJVBxsCTyWPKDkUoXKJl7aWrnwSOdnnHjKftnCea9ry8nj7aSWNfFJvOFWZ/wSEoOeX0RbfhEoe/3s07f6HB92oYbVFbOgKUoKJs+1QVANv3yO5mRpz/aS/sjujJf+917VNeihoU8J77e0yAdpFpJGrdsxsCPHU+p3eiEoS92RGmaoYGbcJwd5jpHcGFC/a+uvZBLyPyAL0U4SbyxFlRACH6Jm/HdyTCtIemXYP8VWXJZoNzljEgvIMFsVOW5zfRyQVFr367ZJ4zsl71y/l7nmLflBKu6rPRSavz8rsBUr0OXSBXLTCx1TmV/E+H8tC9aGkBuAuj363rwabKyN8+T94KVx7DQx0ntxExV6/EKULvK/yP8wXB3Hh8N945SBj57DfwlYZHZ625vgdTw+GJaQHVYpRULONl+zGEGG4IAfDokDAOnpCAQK7TApu+SusVOKPKZC+rCQZHPULmq6p2fhCJmpYo1308yQJzdKiSpDkx5wRC2JaBPH8SFsvoUlojCivrgddAq1fwjkZ0hzqoBoJTNXGOK5RseTF1e/rCN8LSGf+L2ygPC4AEreo/zwB3ic0QI="
